// Stable alias so all code can reference `Env` instead of the generated `CloudflareBindings`.
// `CloudflareBindings` is generated by `wrangler types` in worker-configuration.d.ts.
type Env = CloudflareBindings;
