import { Hono } from "hono";
import { tokenMiddleware } from "./middleware/token";
import { accessMiddleware } from "./middleware/access";
import { observabilityMiddleware } from "./middleware/observability";
import { greader } from "./handlers/greader";
import { dashboardHandler } from "./handlers/dashboard";
import { tokensApiHandler } from "./handlers/tokens_api";
import { scheduled } from "./handlers/cron";
import { FeedPollingWorkflow } from "./workflows/feed_polling";
import type { Variables } from "./types/context";

// Env is generated by `wrangler types` from wrangler.jsonc + .dev.vars
const app = new Hono<{ Bindings: Env; Variables: Variables }>();

// Enrich logger with request context (correlation ID, CF properties) and create
// a request-scoped wide event before any route handler runs.
app.use("*", observabilityMiddleware);

// ---------------------------------------------------------------------------
// GReader API — token auth via D1 lookup (see middleware/token.ts)
// ---------------------------------------------------------------------------

// /reader/* requires token auth; /accounts/ClientLogin does not (it IS the auth entry point)
// Both bare paths and the /api/greader.php/* prefix used by FreshRSS clients (e.g. Current) are supported.
app.use("/reader/*", tokenMiddleware);
app.use("/api/greader.php/reader/*", tokenMiddleware);
app.route("/", greader);
app.route("/api/greader.php", greader);

// ---------------------------------------------------------------------------
// Management UI (Cloudflare Access protected)
// ---------------------------------------------------------------------------

// The whole React dashboard (pages and JSON API) requires a valid
// Cloudflare Access JWT.
app.use("/app/*", accessMiddleware);

// Dashboard JSON API for the React management client (under /app/api/*)
app.route("/", dashboardHandler);
app.route("/", tokensApiHandler); // /app/api/tokens

// Logout: redirect to Cloudflare Access logout endpoint on the same domain
app.get("/auth/logout", (c) => {
  const { protocol, host } = new URL(c.req.url);
  return c.redirect(`${protocol}//${host}/cdn-cgi/access/logout`);
});

// /app → React client's default route (client routes resolve via the
// static-asset SPA fallback in wrangler.jsonc)
app.get("/app", (c) => c.redirect("/app/overview"));

app.get("/", (c) => c.redirect("/app"));

// Workers module export — fetch handler + scheduled cron handler + Workflow class
export default {
  fetch: app.fetch.bind(app),
  scheduled,
};

export { FeedPollingWorkflow };
