import { Hono } from 'hono'
import { tokenMiddleware } from './middleware/token'
import { accessMiddleware } from './middleware/access'
import { greader } from './handlers/greader'
import { tokensHandler } from './handlers/tokens'
import { feedsUiHandler } from './handlers/feeds_ui'
import { importHandler } from './handlers/import'
import { metricsHandler } from './handlers/metrics'
import { scheduled } from './handlers/cron'
import { FeedPollingWorkflow } from './workflows/feed_polling'

// Hono context variables set by middleware
type Variables = {
  userId: string
  email: string
}

// Env is generated by `wrangler types` from wrangler.jsonc + .dev.vars
const app = new Hono<{ Bindings: Env; Variables: Variables }>()

// ---------------------------------------------------------------------------
// GReader API (hardcoded token auth — replaced with D1 lookup in Phase 8)
// ---------------------------------------------------------------------------

// /reader/* requires token auth; /accounts/ClientLogin does not (it IS the auth entry point)
// Both bare paths and the /api/greader.php/* prefix used by FreshRSS clients (e.g. Current) are supported.
app.use('/reader/*', tokenMiddleware)
app.use('/api/greader.php/reader/*', tokenMiddleware)
app.route('/', greader)
app.route('/api/greader.php', greader)

// ---------------------------------------------------------------------------
// Management UI (Cloudflare Access protected)
// ---------------------------------------------------------------------------

// All management UI routes require a valid Cloudflare Access JWT
app.use('/app/*',    accessMiddleware)
app.use('/tokens/*', accessMiddleware)
app.use('/feeds/*',  accessMiddleware)
app.use('/import',   accessMiddleware)

app.route('/', metricsHandler)  // GET /app/metrics

// Logout: redirect to Cloudflare Access logout endpoint on the same domain
app.get('/auth/logout', (c) => {
  const { protocol, host } = new URL(c.req.url)
  return c.redirect(`${protocol}//${host}/cdn-cgi/access/logout`)
})

// /app → redirect to default tab (metrics)
app.get('/app', (c) => c.redirect('/app/metrics'))

// Management UI routes
app.route('/', tokensHandler)   // GET /app/access, POST /tokens/generate, DELETE /tokens/:id
app.route('/', feedsUiHandler)  // GET /app/feeds
app.route('/', importHandler)   // POST /import

app.get('/', (c) => c.text('OK'))

// Workers module export — fetch handler + scheduled cron handler + Workflow class
export default {
  fetch:     app.fetch.bind(app),
  scheduled,
}

export { FeedPollingWorkflow }
